<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBqgWIL6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBqgWIL6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBqgWIL6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBqgWIL6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBqgWIL6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BqgWIL6',
    'container.build_id' => '29f14409',
    'container.build_time' => 1646389127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBqgWIL6');
