<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7r5OxhR\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7r5OxhR/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7r5OxhR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container7r5OxhR\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container7r5OxhR\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '7r5OxhR',
    'container.build_id' => 'a9eb3e55',
    'container.build_time' => 1646334501,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7r5OxhR');
